version: '3'

services:
  cli:
    build:
      context: ./
      dockerfile: ./cli/Dockerfile
    profiles: ["cli"]
    hostname: cli.lauth.local
    networks:
      default:
        aliases: [ "cli" ]
    volumes:
      - ./cli:/lauth/cli
      - ./lib:/lauth/lib
    environment:
      - LAUTH_CLI_API_URL=http://api.lauth.local:9292
      - LAUTH_CLI_API_DB_URL=mysql2://mysql@db.lauth.local/mysql?encoding=utf8mb4
    command:
      - /bin/bash
      - "-c"
      - "bin/standardrb && bin/rspec && bin/cucumber"

  api:
    build:
      context: ./
      dockerfile: ./api/Dockerfile
    profiles: ["api"]
    hostname: api.lauth.local
    networks:
      default:
        aliases: ["api"]
    ports:
      - "9292:9292"
    volumes:
      - ./api:/lauth/api
      - ./lib:/lauth/lib
    environment:
      - LAUTH_API_DB_HOST=db.lauth.local
      - LAUTH_API_DB_DATABASE=mysql
      - LAUTH_API_DB_USER=mysql
    command:
      - /bin/bash
      - "-c"
      - "bundle exec rake db:migrate && bin/rackup --host 0.0.0.0"

  mariadb:
    image: bitnami/mariadb
    hostname: db.lauth.local
    networks:
      default:
        aliases: [ "db" ]
    ports:
      - "3306:3306"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_DATABASE=mysql
      - MARIADB_USER=mysql
      - MARIADB_PASSWORD=
      - TZ=America/Detroit

networks:
  default:
