---
services:
  cli:
    build:
      context: ./
      dockerfile: ./cli/Dockerfile
    profiles: ["test", "cli"]
    volumes:
      - ./cli:/lauth/cli
      - ./lib:/lauth/lib
      # - gem_cache:/gems
    command:
      - /bin/bash
      - "-c"
      - "bin/standardrb && bin/rspec && bin/cucumber"

  api:
    build:
      context: ./
      dockerfile: ./api/Dockerfile
    depends_on:
      - mariadb
    hostname: api.lauth.local
    networks:
      default:
        aliases: ["api"]
    ports:
      - "9292:9292"
    volumes:
      - ./api:/lauth/api
      - ./lib:/lauth/lib
      # - gem_cache:/gems

  mariadb:
    image: bitnami/mariadb
    hostname: db.lauth.local
    networks:
      default:
        aliases: ["db"]
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./db:/sql
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_DATABASE=lauth
      - MARIADB_USER=lauth
      - MARIADB_PASSWORD=lauth
      - TZ=America/Detroit

  apache:
    build: ./module
    # platform: linux/amd64
    ports:
      - "8888:80"
    hostname: "www.lauth.local"
    networks:
      default:
        aliases: ["apache"]
    volumes:
      - ./module:/module

  test:
    build:
      context: ./
      dockerfile: ./test/Dockerfile
    depends_on:
      - api
      - apache
      - mariadb
    profiles: ["test"]
    volumes:
      - ./test:/test
      # - gem_cache:/gems

  dbsetup:
    profiles: ["setup"]
    image: bitnami/mariadb
    depends_on:
      - mariadb
    restart: "no"
    volumes:
      - ./db:/sql
    entrypoint:
      - /bin/bash
      - "-c"
      - "sleep 10 && /sql/setup.sh -u lauth -p lauth -h db.lauth.local lauth"


volumes:
  # gem_cache:
  mariadb_data:

networks:
  default:
