version: '3'

services:
  api:
    build:
      context: ./
      dockerfile: ./api/Dockerfile
    profiles: ["api"]
    hostname: api.lauth.local
    networks:
      default:
        aliases: ["api"]
    ports:
      - "9292:9292"
    volumes:
      - ./api:/lauth/api
      - ./lib:/lauth/lib
    environment:
      - LAUTH_API_DB_HOST=db.lauth.local
      - LAUTH_API_DB_DATABASE=mysql
      - LAUTH_API_DB_USER=mysql
    command:
      - /bin/bash
      - "-c"
      - "bundle exec rake db:migrate && bin/rspec"

  mariadb:
    image: bitnami/mariadb
    hostname: db.lauth.local
    networks:
      default:
        aliases: [ "db" ]
    ports:
      - "3306:3306"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_DATABASE=mysql
      - MARIADB_USER=mysql
      - MARIADB_PASSWORD=
      - TZ=America/Detroit

networks:
  default:
