---
services:
  app:
    image: lauth-app:unstable-dev-${RUBY_VERSION:-3.2.2}${RUBY_SLIM:--slim}
    build:
      context: ./
      dockerfile: ./lauth/Dockerfile
      target: development
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    hostname: app.lauth.local
    networks:
      default:
        aliases: ["app"]
    ports:
      - "127.0.0.1:2300:2300"
    depends_on:
      mariadb:
        condition: "service_healthy"
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://app.lauth.local:2300", "--output", "/dev/null", "--silent" ]
      interval: "5s"
      timeout: "2s"
      retries: 3
    volumes:
      - ./lauth:/lauth/lauth

  app-dev:
    image: lauth-app:unstable-dev-${RUBY_VERSION:-3.2.2}${RUBY_SLIM:--slim}
    profiles: ["test"]
    build:
      context: ./
      dockerfile: ./lauth/Dockerfile
      target: development
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    depends_on:
      mariadb:
        condition: "service_healthy"
    volumes:
      - ./lauth:/lauth/lauth
    command: ["rspec"]

  mariadb:
    image: bitnami/mariadb
    hostname: db.lauth.local
    networks:
      default:
        aliases: ["db"]
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mariadb_data:/bitnami/mariadb
      - ./db:/sql
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_DATABASE=lauth
      - MARIADB_USER=lauth
      - MARIADB_PASSWORD=lauth
      - TZ=America/Detroit
    healthcheck:
      test: ["CMD", "mariadb-admin", "-u", "root", "status"]
      interval: "10s"
      timeout: "10s"
      retries: 3

  apache:
    image: lauth-apache:unstable
    build:
      context: ./
      dockerfile: ./apache/Dockerfile
      target: server
    ports:
      - "127.0.0.1:8888:80"
    hostname: "www.lauth.local"
    networks:
      default:
        aliases: ["apache"]
    healthcheck:
      test: ["CMD", "http-check", "http://www.lauth.local"]
      interval: "5s"
      timeout: "2s"
      retries: 3

  module:
    profiles: [ "dev" ]
    image: lauth-mod-lauth:unstable-dev
    build:
      context: ./
      dockerfile: ./apache/Dockerfile
      target: tests
    environment:
      - LAUTH_TEST_API_URL=http://mock-api:9000
    volumes:
      - ./apache/client:/lauth/apache/client
      - ./apache/module:/lauth/apache/module
      - build_cache:/lauth/apache/build

  mock-api:
    profiles: [ "test", "integration" ]
    image: lauth-apache:unstable-dev
    build:
      context: ./
      dockerfile: ./apache/Dockerfile
      target: tests
    hostname: mock-api.lauth.local
    networks:
      default:
        aliases: ["mock-api"]
    ports:
      - "127.0.0.1:9000:9000"
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://127.0.0.1:9000", "--output", "/dev/null", "--silent" ]
      interval: "10s"
      timeout: "10s"
      retries: 3
    command: ["./http-service", "9000"]

  client-tests:
    profiles: [ "test", "integration" ]
    image: lauth-liblauth:unstable-dev
    build:
      context: ./
      dockerfile: ./apache/Dockerfile
      target: client-tests
    depends_on:
      mock-api:
        condition:
          "service_healthy"
    environment:
      - LAUTH_TEST_API_URL=http://mock-api.lauth.local:9000

  test:
    profiles: ["test"]
    image: lauth-test:unstable-${RUBY_VERSION:-3.2.2}${RUBY_SLIM:--slim}
    build:
      context: ./
      dockerfile: ./test/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    depends_on:
      apache:
        condition: "service_healthy"
      app:
        condition: "service_healthy"
      mariadb:
        condition: "service_healthy"
    volumes:
      - ./test:/lauth/test

  dbsetup:
    profiles: ["setup"]
    image: bitnami/mariadb
    depends_on:
      mariadb:
        condition: "service_healthy"
    restart: "no"
    volumes:
      - ./db:/sql
    command:
      - /bin/bash
      - "-c"
      - "/sql/setup.sh -u lauth -p lauth -h db.lauth.local lauth_development && /sql/setup.sh -u lauth -p lauth -h db.lauth.local lauth_test"

volumes:
  mariadb_data:
  build_cache:

networks:
  default:
