version: '3'

services:
  cli:
    build: ./cli
    volumes:
      - ./cli:/cli
      - gem_cache:/gems
    env_file:
      - cli/.env
    command:
      - /bin/bash
      - "-c"
      - "bin/standardrb && bin/rspec && bin/cucumber"

  api:
    build: ./api
    volumes:
      - ./api:/api
      - gem_cache:/gems
    env_file:
      - api/.env
    command:
      - /bin/bash
      - "-c"
      - "bin/standardrb && bin/rspec && bin/cucumber"

  apache:
    build: ./module
    # platform: linux/amd64
    ports:
      - "8888:80"
    volumes:
      - ./module:/module

volumes:
  gem_cache:
