---
services:
  app:
    build:
      context: ./
      dockerfile: ./lauth/Dockerfile
      target: development
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    ports:
      - "127.0.0.1:2300:2300"
    depends_on:
      mariadb:
        condition: "service_healthy"
    volumes:
      - ./lauth:/lauth/lauth

  app-dev:
    profiles: ["test"]
    build:
      context: ./
      dockerfile: ./lauth/Dockerfile
      target: development
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    depends_on:
      mariadb:
        condition: "service_healthy"
    volumes:
      - ./lauth:/lauth/lauth
    command: ["rspec"]

  mariadb:
    image: bitnami/mariadb
    hostname: db.lauth.local
    networks:
      default:
        aliases: ["db"]
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./db:/sql
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_DATABASE=lauth
      - MARIADB_USER=lauth
      - MARIADB_PASSWORD=lauth
      - TZ=America/Detroit
    healthcheck:
      test: ["CMD", "mariadb-admin", "-u", "root", "status"]
      interval: "10s"
      timeout: "10s"
      retries: 3
      start_period: "2s"
      start_interval: "1s"

  apache:
    build:
      context: ./
      dockerfile: ./apache/Dockerfile
      target: server
    ports:
      - "127.0.0.1:8888:80"
    hostname: "www.lauth.local"
    networks:
      default:
        aliases: ["apache"]
    healthcheck:
      test: ["CMD", "http-check", "http://www.lauth.local"]
      interval: "60s"
      timeout: "2s"
      retries: 3
      start_period: "3s"
      start_interval: "1s"

  module:
    build:
      context: ./
      dockerfile: ./apache/Dockerfile
      target: tests
    profiles: ["dev"]
    volumes:
      - ./apache/client:/lauth/apache/client
      - ./apache/module:/lauth/apache/module
      - build_cache:/lauth/apache/build

  mock-api:
    build:
      context: ./
      dockerfile: ./apache/Dockerfile
      target: tests
    profiles: ["integration"]
    ports:
      - "127.0.0.1:9000:9000"
    command: ["./http-service", "9000"]

  client-tests:
    build:
      context: ./
      dockerfile: ./apache/Dockerfile
      target: client-tests
    profiles: ["test"]

  test:
    profiles: ["test"]
    build:
      context: ./
      dockerfile: ./test/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    depends_on:
      apache:
        condition: "service_healthy"
      mariadb:
        condition: "service_healthy"
    volumes:
      - ./test:/lauth/test

  dbsetup:
    profiles: ["setup"]
    image: bitnami/mariadb
    depends_on:
      mariadb:
        condition: "service_healthy"
    restart: "no"
    volumes:
      - ./db:/sql
    command:
      - /bin/bash
      - "-c"
      - "/sql/setup.sh -u lauth -p lauth -h db.lauth.local lauth_development && /sql/setup.sh -u lauth -p lauth -h db.lauth.local lauth_test"

volumes:
  mariadb_data:
  build_cache:

networks:
  default:
