version: '3'

services:
  cli:
    build: ./cli
    volumes:
      - ./cli:/cli
      - gem_cache:/gems
    env_file:
      - cli/.env
    command:
      - /bin/bash
      - "-c"
      - "bin/standardrb && bin/rspec && bin/cucumber"

  api:
    build: ./api
    volumes:
      - ./api:/api
      - gem_cache:/gems
    env_file:
      - api/.env
    command:
      - /bin/bash
      - "-c"
      - "bin/standardrb && bin/rspec && bin/cucumber"

  mariadb:
    image: bitnami/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./db:/sql
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_DATABASE=lauth
      - MARIADB_USER=lauth
      - MARIADB_PASSWORD=lauth
      - TZ=America/Detroit

  apache:
    build: ./module
    # platform: linux/amd64
    ports:
      - "8888:80"
    volumes:
      - ./module:/module

volumes:
  gem_cache:
  mariadb_data:
