version: '3'

services:
  cli:
    build:
      context: ./
      dockerfile: ./cli/Dockerfile
    depends_on:
      - api
    restart: "no"
    hostname: cli.lauth.local
    networks:
      default:
        aliases: [ "cli" ]
    volumes:
      - ./cli:/lauth/cli
      - ./lib:/lauth/lib
      - ./db:/lauth/db
    environment:
      - LAUTH_API_DB_HOST=db.lauth.local
      - LAUTH_API_DB_DATABASE=lauth
      - LAUTH_API_DB_USER=lauth
      - LAUTH_API_DB_PASSWORD=lauth
    command:
      - /bin/bash
      - "-c"
      - "sleep 40 && bin/lauth --url=http://api.lauth.local:9292 initconfig && bin/standardrb && bin/rspec && bin/cucumber"

  api:
    build:
      context: ./
      dockerfile: ./api/Dockerfile
    depends_on:
      - mariadb
    hostname: api.lauth.local
    networks:
      default:
        aliases: ["api"]
    ports:
      - "9292:9292"
    volumes:
      - ./api:/lauth/api
      - ./lib:/lauth/lib
    environment:
      - LAUTH_API_DB_HOST=db.lauth.local
      - LAUTH_API_DB_DATABASE=lauth
      - LAUTH_API_DB_USER=lauth
      - LAUTH_API_DB_PASSWORD=lauth
    command:
      - /bin/bash
      - "-c"
      - "sleep 30 && bundle exec rake db:migrate && bin/rackup --host 0.0.0.0"

  mariadb:
    image: bitnami/mariadb
    hostname: db.lauth.local
    networks:
      default:
        aliases: [ "db" ]
    ports:
      - "3306:3306"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_DATABASE=lauth
      - MARIADB_USER=lauth
      - MARIADB_PASSWORD=lauth
      - TZ=America/Detroit

  mariadbsetup:
    image: bitnami/mariadb
    depends_on:
      - mariadb
    restart: "no"
    volumes:
      - ./db:/sql
    entrypoint:
      - /bin/bash
      - "-c"
      - "sleep 20 && /sql/setup.sh -u lauth -p lauth -h db.lauth.local lauth"

networks:
  default:
