# frozen_string_literal: true

source "https://rubygems.org"

HANAMI_VERSION = "2.1.0.rc2"

gem "hanami", "~> #{HANAMI_VERSION}"
gem "hanami-router", "~> #{HANAMI_VERSION}"
gem "hanami-controller", "~> #{HANAMI_VERSION}"
gem "hanami-validations", "~> #{HANAMI_VERSION}"
gem "hanami-view", "~> #{HANAMI_VERSION}"
gem "hanami-assets", "~> #{HANAMI_VERSION}"

gem "dry-types", "~> 1.0", ">= 1.6.1"
gem "puma"
gem "rake"

gem "rom", "~> 5.3"
gem "rom-factory", "~> 0.11.0"
gem "rom-sql", "~> 3.6", git: "https://github.com/mlibrary/rom-sql.git", tag: "v3.6.2-0.1"
gem "mysql2"

group :development do
  gem "hanami-webconsole", "~> #{HANAMI_VERSION}"
  gem "guard-puma"
end

group :development, :test do
  gem "dotenv"
  gem "standard"
end

group :cli, :development do
  gem "hanami-reloader", "~> #{HANAMI_VERSION}"
end

group :cli, :development, :test do
  gem "hanami-rspec", "~> #{HANAMI_VERSION}"
end

group :test do
  gem "rack-test"
  gem "database_cleaner-sequel"
end
