source "https://rubygems.org"

gem "dotenv", "~> 2.7.6"
gem "gli"
gem "ipaddress"
gem "mysql2", "~> 0.5.4"
gem "rom", "~> 5.2.6"
gem "rom-sql", "~> 3.5.0"
gem "rom-http", git: "https://github.com/rom-rb/rom-http", ref: "f0507e52ba5f39a42ccfd24b0b6b88b86984c8de"

# testing

gem "cucumber", "~> 8.0.0"
gem "database_cleaner-sequel"
gem "rack-test"
gem "rake"
gem "rom-factory"
gem "rspec", "~> 3.11"
gem "sequel"
gem "sqlite3"
gem "standard", "~> 1.12"
