source "https://rubygems.org"

gem "aruba", "~> 2.1.0"
gem "cucumber", "~> 8.0.0"
gem "dotenv", "~> 2.7.6"
gem "dry-cli", "~> 0.7.0"
gem "faraday", "~> 2.3.0"
gem "rspec", "~> 3.11"
gem "standard", "~> 1.12"
