---
services:
  app:
    build:
      context: ../
      dockerfile: ./lauth/Dockerfile
      target: development
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    hostname: app.lauth.local
    networks:
      default:
        aliases: ["app"]
    ports:
      - "2300:2300"
      - "1234:1234" # RubyMine
    depends_on:
      mariadb:
        condition: "service_healthy"
    volumes:
      - .:/lauth/lauth
    command: ["sleep", "infinity"]

  mariadb:
    image: bitnami/mariadb
    hostname: db.lauth.local
    networks:
      default:
        aliases: ["db"]
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/bitnami/mariadb
      - ../db:/sql
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_DATABASE=lauth
      - MARIADB_USER=lauth
      - MARIADB_PASSWORD=lauth
      - TZ=America/Detroit
    healthcheck:
      test: ["CMD", "mariadb-admin", "-u", "root", "status"]
      interval: "10s"
      timeout: "10s"
      retries: 3

  dbsetup:
    profiles: ["setup"]
    image: bitnami/mariadb
    depends_on:
      mariadb:
        condition: "service_healthy"
    restart: "no"
    volumes:
      - ../db:/sql
    command:
      - /bin/bash
      - "-c"
      - "/sql/setup.sh -u lauth -p lauth -h db.lauth.local lauth_development && /sql/setup.sh -u lauth -p lauth -h db.lauth.local lauth_test"

volumes:
  mariadb_data:

networks:
  default:
