#!/usr/bin/env bash

if [ ! -f "VERSION" ]; then
  echo "VERSION file is missing!"
  exit -1
fi

fpm --input-type dir \
  --output-type deb \
  --architecture native \
  --deb-generate-changes \
  \
  --deb-dist bullseye \
  --depends apache2 \
  --depends libstdc++6 \
  --depends libssl1.1 \
  --exclude 'usr/lib/python3.9' \
  \
  --name libapache2-mod-lauth \
  --version "$(<VERSION)" \
  --after-install postinst \
  --url 'https://github.com/mlibrary/lauth' \
  --maintainer 'University of Michigan Library Information Technology' \
  --description 'Library Authentication/Authorization Module for Apache2' \
  \
  conf/=/etc/apache2/mods-available \
  lib/=/usr/lib \
  mod_lauth.so=/usr/lib/apache2/modules/mod_lauth.so
