---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: lauth
  name: api
  namespace: $ENVSUBST_NAMESPACE
spec:
  selector:
    app: lauth
  clusterIP: None
  ports:
    - port: 9292
      name: api
