---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: lauth
  name: db-persistent-volume
  namespace: $ENVSUBST_NAMESPACE
spec:
  accessModes:
    - ReadWriteOnce                 # This way, only one pod can access this at a time.
  storageClassName: rook-ceph-block # This is how you specify the block storage backend.
  resources:
    requests:
      storage: 500Mi                # This will reserve 500Mi; this number can go up but never down.
