---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: lauth
  name: db
  namespace: $ENVSUBST_NAMESPACE
spec:
  selector:
    app: lauth
  clusterIP: None
  ports:
    - port: 3306
      name: db
