apiVersion: v1
kind: Secret
metadata:
  labels:
    app: lauth
  name: lauth-secret
  namespace: $ENVSUBST_NAMESPACE
type: Opaque
stringData:
  api_root_user: "$ENVSUBST_API_ROOT_USER"
  api_root_password: "$ENVSUBST_API_ROOT_PASSWORD"
  db_root_password: "$ENVSUBST_DB_ROOT_PASSWORD"
  db_database: "$ENVSUBST_DB_DATABASE"
  db_user: "$ENVSUBST_DB_USER"
  db_password: "$ENVSUBST_DB_PASSWORD"
