---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: lauth
  name: api
  namespace: lauth-testing
spec:
  selector:
    app: lauth
  clusterIP: None
  ports:
    - port: 9292
      name: api
    - port: 9394
      name: metrics
