source "https://rubygems.org"

gem "config", "~> 4.0.0"
gem "dotenv", "~> 2.7.6"
gem "hanami-api", git: "https://github.com/hanami/api", ref: "10c0d3b79232e933dd4e9e74bb2c6feb4a1f539e"
gem "ipaddress"
gem "mysql2", "~> 0.5.4"
gem "puma", "~> 5.6"
gem "rom", "~> 5.2.6"
gem "rom-http", git: "https://github.com/rom-rb/rom-http", ref: "f0507e52ba5f39a42ccfd24b0b6b88b86984c8de"
gem "rom-sql", "~> 3.5.0"
gem "yabeda-prometheus"
# gem 'yabeda-prometheus-mmap'
gem "yabeda-puma-plugin"

# testing
gem "cucumber", "~> 8.0.0"
gem "database_cleaner-sequel"
gem "rack-test"
gem "rake"
gem "rom-factory"
gem "rspec", "~> 3.11"
gem "sequel"
gem "standard", "~> 1.12"
