#saved so that I can have a workflow to try out in a branch
name: Scratch

on:
  release:
    types: [ released ]
  workflow_dispatch:
    inputs:
      tag:
        description: release
        required: true

jobs:
  build-staging:
    name: Build staging ${{ github.event.inputs.tag }}
    uses: mlibrary/platform-engineering-workflows/.github/workflows/build-production.yml@v1
    with:
      image_name: ${{ vars.IMAGE_NAME }}
      tag: ${{ github.event.inputs.tag }}
      dockerfile: ./lauth/Dockerfile
    secrets: inherit

  deploy-staging:
    needs: build-staging
    name: Deploy to staging
    uses: mlibrary/platform-engineering-workflows/.github/workflows/deploy.yml@v1
    with:
      image: ghcr.io/mlibrary/${{ vars.IMAGE_NAME }}:${{ github.event.inputs.tag }}
      file: environments/lauth/staging/web-image.txt
      CONFIG_REPO_RW_APP_ID: ${{ vars.CONFIG_REPO_RW_APP_ID }}
      CONFIG_REPO_RW_INSTALL_ID: ${{ vars.CONFIG_REPO_RW_INSTALL_ID }}
      CONFIG_REPO_FULL_NAME: ${{ vars.CONFIG_REPO_FULL_NAME }}
    secrets: inherit
