---
name: Build APACHE latest from main (or manually from a selected branch)

on:
  workflow_dispatch:  # This allows to kick-off the action manually from GitHub Actions
  push:
    branches: [ main ]  # This watches pushes to the "main" branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          context: ./
          target: server
          push: true
          tags: 'ghcr.io/mlibrary/lauth/lauth-apache:${{ github.sha }}, ghcr.io/mlibrary/lauth/lauth-apache:latest'
          file: ./apache/Dockerfile

      - name: Build .deb packages
        uses: docker/build-push-action@v5
        with:
          context: ./
          target: packages
          push: false
          load: true
          tags: 'lauth-debs:latest'
          file: ./apache/Dockerfile

      - uses: shrink/actions-docker-extract@v3
        id: extract
        with:
          image: lauth-debs:latest
          path: /debs/out/.
          destination: dist

      - name: Archive lauth-apache .deb packages
        uses: actions/upload-artifact@v4
        with:
          name: lauth-apache-debs_${{ github.sha }}
          path: dist/*
