---
name: Build Lauth webapp
#description: Builds the webapp (api and admin) from main or manually from a selected branch

on:
  workflow_dispatch:  # This allows to kick-off the action manually from GitHub Actions
  push:
    branches: [ main ]  # This watches pushes to the "main" branch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: 'ghcr.io/mlibrary/lauth/lauth:${{ github.sha }}, ghcr.io/mlibrary/lauth/lauth:latest'
          file: lauth/Dockerfile
          target: production
          platforms: linux/amd64, linux/arm64

      - name: Image digest
        run: |
          echo '${{ steps.docker_build.outputs.digest }}'
