---
name: Build APACHE latest from main (or manually from a selected branch)

on:
  workflow_dispatch:  # This allows to kick-off the action manually from GitHub Actions
  push:
    branches: [ main ]  # This watches pushes to the "main" branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@371161bbe7024a29a25c5e19bfcbc0804fe9ad2c # v4.5.2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: ./
          target: server
          push: true
          tags: 'ghcr.io/mlibrary/lauth/lauth-apache:${{ github.sha }}, ghcr.io/mlibrary/lauth/lauth-apache:latest'
          file: ./apache/Dockerfile

      - name: Build .deb packages
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: ./
          target: packages
          push: false
          load: true
          tags: 'lauth-debs:latest'
          file: ./apache/Dockerfile

      - uses: shrink/actions-docker-extract@4be21666a95f7954632039d78bc77f25ff3b0b31 # v4.0.0
        id: extract
        with:
          image: lauth-debs:latest
          path: /debs/out/.
          destination: dist

      - name: Archive lauth-apache .deb packages
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: lauth-apache-debs_${{ github.sha }}
          path: dist/*
