name: Build API latest from main

on:
  workflow_dispatch:
  push:
    branches: [ kubernetes ] # This watches the branch called "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: 'ghcr.io/mlibrary/lauth/lauth-api:${{ github.sha }}, ghcr.io/mlibrary/lauth/lauth-api:latest'
          file: api/Dockerfile.prod
