---
name: Continuous Integration

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:

  ci:
    runs-on: ubuntu-latest
    name: ${{ matrix.suite }} - Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        suite:
          - 'app'
          - 'test'
        ruby:
          - '3.2.2'
#          - '3.1.4'
#          - '3.0.4'

    steps:
      - uses: actions/checkout@v4
      - name: Setup Database
        run: docker compose up dbsetup

      - name: Create .env
        run: |
          echo "UID=$(id -u)" > .env
          echo "GID=$(id -g)" >> .env

      - if: matrix.suite == 'app'
        run: |
          docker compose build --build-arg RUBY_VERSION=${{ matrix.ruby }} app-dev
          docker compose run app-dev
      - if: matrix.suite == 'test'
        run: |
          docker compose build --build-arg RUBY_VERSION=${{ matrix.ruby }} app apache
          docker compose run test

      - name: Breakpoint if tests failed
        if: failure()
        uses: namespacelabs/breakpoint-action@v0
        with:
          duration: 30m
          authorized-users: botimer
