---
name: Continuous Integration

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:

  ci:
    runs-on: ubuntu-latest
    name: ${{ matrix.suite }} - Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        suite:
          - 'api'
          - 'cli'
          - 'test'
        ruby:
#          - '3.2.2' sqlite3-1.5.3-x86_64-linux requires ruby version < 3.2.dev, >= 2.6, which is incompatible with the current version, ruby 3.2.2p53
          - '3.1.4'
          - '3.0.4'
#          - '2.7.6' hanami-api was resolved to 0.2.0, which depends on Ruby (>= 3.0.0)

    steps:
      - uses: actions/checkout@v4
      - name: Setup Database
        run: docker compose up dbsetup

      - if: matrix.suite == 'api'
        run: |
          rm -f /lauth/api/Gemfile.lock
          docker compose build --build-arg RUBY_VERSION=${{ matrix.ruby }} api
          docker compose run api bundle exec rake db:migrate
          docker compose run api bin/standardrb
          docker compose run api bin/rspec
          docker compose run api bin/cucumber
      - if: matrix.suite == 'cli'
        run: |
          rm -f /lauth/api/Gemfile.lock
          rm -f /lauth/cli/Gemfile.lock
          docker compose build --build-arg RUBY_VERSION=${{ matrix.ruby }} api cli
          docker compose up -d api
          docker compose exec api bundle exec rake db:migrate
          docker compose run cli
      - if: matrix.suite == 'test'
        run: |
          rm -f /lauth/api/Gemfile.lock
          rm -f /lauth/test/Gemfile.lock
          docker compose build --build-arg RUBY_VERSION=${{ matrix.ruby }} api apache
          docker compose run test
