---
name: Continuous Integration

on:
  workflow_dispatch:
#  push:
#  pull_request:

#env:
#  LAUTH_API_DB_HOST: 127.0.0.1
#  LAUTH_API_DB_DATABASE: test
#  LAUTH_API_DB_USER: user
#  LAUTH_API_DB_PASSWORD: password
#  ALLOW_EMPTY_PASSWORD: yes
#  MARIADB_DATABASE: test
#  MARIADB_USER: user
#  MARIADB_PASSWORD: password
#  TZ: America/Detroit

jobs:

  ci:
    runs-on: ubuntu-latest
    name: ${{ matrix.suite }} - Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        suite:
          - 'api'
          - 'cli'
          - 'test'
        ruby:
#          - '3.2.2' sqlite3-1.5.3-x86_64-linux requires ruby version < 3.2.dev, >= 2.6, which is incompatible with the current version, ruby 3.2.2p53
          - '3.1.4'
          - '3.0.4'
#          - '2.7.6' hanami-api was resolved to 0.2.0, which depends on Ruby (>= 3.0.0)

    steps:
      - uses: actions/checkout@v4
      - name: Setup Database
        run: docker compose up dbsetup

      - if: matrix.suite == 'api'
        run: |
          rm -f /lauth/api/Gemfile.lock
          docker compose build --build-arg RUBY_VERSION=${{ matrix.ruby }}
          docker compose run api bundle exec rake db:migrate
          docker compose run api bin/standardrb
          docker compose run api bin/rspec
          docker compose run api bin/cucumber
      - if: matrix.suite == 'cli'
        run: |
          rm -f /lauth/api/Gemfile.lock
          rm -f /lauth/cli/Gemfile.lock
          docker compose build --build-arg RUBY_VERSION=${{ matrix.ruby }}
          docker compose run api bundle exec rake db:migrate
          docker compose run cli
      - if: matrix.suite == 'test'
        run: |
          rm -f /lauth/api/Gemfile.lock
          rm -f /lauth/test/Gemfile.lock
          docker compose build --build-arg RUBY_VERSION=${{ matrix.ruby }}
          docker compose run test
