name: delete-workflow-runs
on:
  workflow_dispatch:
    inputs:
      days:
        description: 'Number of days.'
        required: true
        default: 7

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@b3018382ca039b53d238908238bd35d1fb14f8ee # v2.1.0
        with:
          #          token: ${{ secrets.AUTH_PAT }}
          #          repository: ${{ github.repository }}
          retain_days: ${{ github.event.inputs.days }}
