name: Deploy to testing namespace

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ 'Build API latest from main' ] # this should match the name at the top of your build workflow
    types: [ 'completed' ] # this will only run when an image is successfully built.

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/setup-kubectl@v1
      - name: Authenticate with kubernetes
        run: |
          mkdir -p ${HOME}/.kube/certs/cluster
          echo ${{ secrets.HATCHER_CLUSTER_CA }} | base64 -d > ${HOME}/.kube/certs/cluster/k8s-ca.crt
          kubectl config set-cluster cluster --certificate-authority=${HOME}/.kube/certs/cluster/k8s-ca.crt --server=https://hatcher.kubernetes.lib.umich.edu
          kubectl config set-credentials default --token=`echo ${{ secrets.HATCHER_TESTING_TOKEN }} | base64 -d`
          kubectl config set-context default --cluster=cluster --user=default --namespace=gkostin-sandbox
          kubectl config use-context default
      - name: Automatic Deploy
        run: kubectl set image deployment web web=ghcr.io/mlibrary/lauth/lauth-api:${{ github.sha }}
