name: Deploy Staging on Release

on:
  release:
    types: [ released ]

jobs:
  build-staging:
    name: Build staging ${{ github.event.release.tag_name }}
    # uses: mlibrary/lauth/.github/workflows/build-production.yml@v1
    uses: ./.github/workflows/build-production.yml
    with:
      image_name: ${{ vars.IMAGE_NAME }}
      tag: ${{ github.event.release.tag_name }}
      dockerfile: ./lauth/Dockerfile
      target: production
    secrets: inherit

  deploy-staging:
    needs: build-staging
    name: Deploy to staging
    uses: mlibrary/platform-engineering-workflows/.github/workflows/deploy.yml@v1
    with:
      image: ghcr.io/mlibrary/${{ vars.IMAGE_NAME }}:${{ github.event.release.tag_name }}
      file: environments/lauth/staging/web-image.txt
      CONFIG_REPO_RW_APP_ID: ${{ vars.CONFIG_REPO_RW_APP_ID }}
      CONFIG_REPO_RW_INSTALL_ID: ${{ vars.CONFIG_REPO_RW_INSTALL_ID }}
      CONFIG_REPO_FULL_NAME: ${{ vars.CONFIG_REPO_FULL_NAME }}
    secrets: inherit
