---
name: gkostin
defaults:
  run:
    shell: bash
    working-directory: scripts
on: [push]
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Present Working Directory
        run: pwd
        shell: bash
      - name: Run Bash Script
        run: ./.github/scripts/gkostin.sh
        shell: bash
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
