cc_library(
  name = "cpp-httplib",
  hdrs = ["httplib.h"],
  strip_include_prefix = ".",
  visibility = ["//visibility:public"],
)

cc_library(
  name = "nlohmann-json",
  hdrs = ["json.hpp"],
  strip_include_prefix = ".",
  visibility = ["//visibility:public"],
)
